name: d_sample
description: Downsampling algorithms for time series data（LTOB, LTTB, LTD, OSI-PI Plot, etc.）Implemented in Dart
version: 1.0.1
repository: https://github.com/Go-oG/d_sample

environment:
  sdk: ^3.2.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
